config/routes.rb
Depot::Application.routes.draw do

  resources :comments

  get "store/index" 
  
  scope '(:locale)' do
     resources :users
     resources :customers
     resources :orders do
			get 'present', :on => :member
			get 'ship', :on => :collection
		end
     resources :line_items
     resources :carts
     resources :products do
        get :who_bought, :on => :member
        post :search, :on=> :collection
     end
     resources :products do
      resources :comments
     end
		 
		controller :store do
			get		'show_product' => :show
		end
		
     root :to => 'store#index', :as => 'store'
     
     controller :customer_admin do
       get "customer_admin/login" => :login, :as => :customer_admin_login
       post "customer_admin/login" => :judge, :as => :customer_admin_login
       get "customer_admin/logout" => :logout, :as => :customer_admin_logout
       get "customer_admin/confirm" => :confirm, :as => :customer_admin_confirm
    end
    
    get 'admin' => 'admin#index'

    controller :sessions do
      get "login" => :new, :as => :login
      post 'login' => :create, :as => :login
      delete 'logout' => :destroy, :as => :logout
		end
		
  end
  
  match '*error_path' => 'errors#routing'









  

 


end

app/views/layouts/application.html.erb
<!-- START:head -->
<!DOCTYPE html>
<html>
<head>
  <title>Pragprog Books Online Store</title>
<!-- START_HIGHLIGHT -->
  <%= stylesheet_link_tag "scaffold" %>
  <%= stylesheet_link_tag "depot", :media => "all" %><!-- <label id="code.slt"/> -->
<!-- END_HIGHLIGHT -->
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %><!-- <label id="code.csrf"/> -->
</head>
<!-- END:head -->
<body id="store">
  <div id="banner">
  		<div id="locale">
  		<%= form_tag store_path do%>
 		<%= select_tag 'set_locale',
 			options_for_select(LANGUAGES, I18n.locale.to_s),
 			:onchange => 'this.form.submit()'%>
 		<% end %>
 		<% if session[:customer_id]%>
 			<%= button_to "logout", customer_admin_logout_url, :method => :get%>
 		<% else %>
 			<%= button_to "login", customer_admin_login_url,:method => :get%> 		
 		<% end %>
		
        <!-- <label id="code.depot.e.title"/> -->
		</div>
		<div id="top_title">
			<%= link_to image_tag("logo1.png"),store_path %>
  			<%= @page_title || t('.title') %>
 	 	</div>
 
 	 <div id="top_buttons">
 	 	<!-- SEARCH FORM IS HERE-->
 	 	<form id="search_box" action="<%= search_products_url :locale=>I18n.locale%>" method="post">			
 	 		<input type="text" autocomplete="off" id="search_query" name="key" />
 	 		<input type="submit" id="search_btn" class="" title="搜索" value="" />
 	 	</form>
 	 	<!-- END SERACH FORM-->
 	 	<table >
 			<tr>
 				<td>
 	 				<a href="/" onblur="Blur(this);" onclick="Focus(this)"><%= t('.home')%></a>
 	 				<a href="/"><%= t('.questions')%></a>
 				 	<a href="/"><%= t('.news')%></a>
 	 				<a href="/"><%= t('.contact')%></a>
 	 			</td>
 	 		</tr>
 		</table>
 	   
 	 
 	 </div>	
 </div>
  <div id="columns">
	<div id="side">
		<% if @cart %>
			<%= hidden_div_if(@cart.line_items.empty?, :id => "cart") do%>
				<%= render @cart%>
			<% end %>
		<% end %>
	  
	  <% if session[:user_id]%>
	  	<br />
	  	<%= link_to "Orders", orders_path %><br />
	  	<%= link_to "Products", products_path %><br />
	  	<%= link_to "Users", users_path %><br />
	  	<%= link_to "Download Administrator Manual", "manuals/AdministratorManual.pdf" %><br />
	  	<br />
	  	<%= button_to 'Logout', logout_path, :method => :delete %>
	  <% else %>
	    <br />
	  	<%= link_to "Download user Manual", "manuals/UserManual.pdf" %><br />
	  <% end %>
  </div>
  <div id="main">
	<%= yield %><!-- <label id="code.depot.e.include"/> -->
  </div>
  <div class="clearboth"></div>
 </div>
 
</body>
</html>

app/views/layouts/main.html.erb
<h1>ht</h1>
<%= yield %>